import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Operations } from '@/components/operations';
// import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "react-vertical-timeline-component/style.min.css";
// import "@/styles/override.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative bg-white dark:bg-gray-900">
        <ThemeProvider attribute="class" defaultTheme="system">
          <Operations />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
